/* Core/Src/audio_i2s.c
 *
 * The I2S consumer side of the audio pipeline.
 *
 * DATA FLOW
 * ---------
 *   USB host -> usbd_audio_if.c -> RingBuffer_Write -> ring_buffer
 *   ring_buffer -> [AudioI2S_RefillHalfA/B] -> audio_i2s_buffer
 *   audio_i2s_buffer -> DMA1_Stream4 -> I2S2 -> MAX98357A -> speaker
 *
 * We are the consumer. We pull mono int16 samples out of the
 * ring buffer and lay them into a stereo-shaped I2S DMA buffer
 * (each mono sample written to BOTH the L and R slot of a frame).
 * The MAX98357A mixes L+R internally, so the speaker hears
 * (L+R)/2 = mono_sample with no amplitude loss.
 *
 * CALLBACK ROUTING
 * ----------------
 * The HAL fires HAL_I2S_TxHalfCpltCallback and HAL_I2S_TxCpltCallback
 * from the DMA1_Stream4 ISR. We don't override those weak symbols
 * here — instead, stm32f4xx_it.c dispatches them to our Refill
 * functions. This keeps the ISR dispatch file as the single
 * "what happens on IRQ X" place.
 */

#include "audio_i2s.h"
#include "ring_buffer.h"
#include "stm32f4xx_hal.h"   /* I2S_HandleTypeDef */
#include <string.h>
#include <math.h>            /* sinf in the acoustic-isolation diagnostic */

/* The I2S2 peripheral handle is generated by CubeMX and lives
 * in main.c. We declare it extern here so this module compiles
 * without depending on main.c's internals. */
extern I2S_HandleTypeDef hi2s2;
extern void Error_Handler(void);

/* The I2S DMA buffer. Zero-initialized at startup so the very
 * first samples (before any USB audio arrives) are silence. */
int16_t audio_i2s_buffer[AUDIO_I2S_BUFFER_SIZE] = {0};

/* ============================================================================
 * ACOUSTIC ISOLATION TEST (temporary diagnostic)
 * ----------------------------------------------
 * When dbg_bypass_usb != 0, the I2S DMA buffer is filled with a generated
 * 1 kHz sine instead of USB/ring audio.  This exercises the EXACT same
 * DMA1_Stream4 -> I2S2 -> MAX98357A -> speaker path as normal playback but
 * bypasses the USB bridge completely.
 *   - generated tone is clean      => the USB/ring data path is the culprit
 *   - generated tone still 200/300Hz-buzzy => amp/power/speaker is the culprit
 * Set dbg_bypass_usb = 0 (SWD/GDB) to restore normal USB playback with no
 * reflash.  Default is 1 so the isolation test runs right after flashing.
 * DELETE this block after the test.
 * ==========================================================================*/
volatile uint8_t dbg_bypass_usb = 1U;
#define GEN_FREQ_HZ    1000.0f
#define GEN_SR         44100.0f
#define GEN_AMP        9000
static uint32_t gen_phase = 0U;

static void audioi2s_fill_generated(uint16_t mono_count, uint16_t stereo_dst)
{
    for (uint16_t i = 0U; i < mono_count; i++)
    {
        /* Phase-continuous running sine so the DMA half/full boundaries
         * never cause a discontinuity while generating. */
        float t = 2.0f * 3.14159265358979f * GEN_FREQ_HZ * ((float)(gen_phase + i)) / GEN_SR;
        int16_t v = (int16_t)((float)GEN_AMP * sinf(t));
        audio_i2s_buffer[stereo_dst + 2U * i]      = v;   /* L */
        audio_i2s_buffer[stereo_dst + 2U * i + 1U] = v;   /* R */
    }
    gen_phase += mono_count;
}

/* How many mono samples fit in one I2S half-buffer.
 * Half = 440 int16 = 220 stereo frames = 220 mono samples. */
#define I2S_HALF_MONO_COUNT  (AUDIO_I2S_BUFFER_SIZE / 2 / 2)   /* 220 */
#define I2S_HALF_BYTES       (I2S_HALF_MONO_COUNT * 2 * sizeof(int16_t))  /* 880 */

/* Scratch for pulling mono samples from the ring before duplicating
 * them into L+R. 220 int16 = 220 mono samples = 5 ms of audio at
 * 44.1 kHz = exactly one half of the I2S buffer's worth.
 *
 * Why a scratch instead of writing directly into the I2S buffer:
 * RingBuffer_Read writes samples contiguously (mono), but the I2S
 * buffer needs them duplicated (L, R, L, R, ...). Easier to do the
 * duplication in a second pass over a small scratch array. */
static int16_t mono_scratch[220];

/* ============================================================================
 * STEP DIAG NSTRUMENTATION (temporary, non-behavioral) — confirm the ~100 Hz
 * artifact source in the consumer path. Read via SWD/GDB while a 1 kHz tone
 * chatters:
 *   - dbg_partial_count rising at ~200/s (5 ms halves) => consumer starvation
 *     (short fills); dbg_partial_short is total missing mono samples.
 *   - dbg_late_gap / dbg_max_gap_ms >0 => a refill callback came late (>6 ms),
 *     so the DMA replayed a partially-refilled half (latency/jitter).
 *   - If BOTH stay ~0 the artifact is not starvation or cadence -> look at
 *     wrap/alignment next.  events/sec = count / (seconds of playback).
 * Remove after the root cause is fixed.
 * ==========================================================================*/
volatile uint32_t dbg_refill_calls;    /* total HalfA+HalfB refills performed  */
volatile uint32_t dbg_partial_count;   /* refills that got < 220 mono samples  */
volatile uint32_t dbg_partial_short;   /* total missing mono samples (deficit) */
volatile uint32_t dbg_late_gap;        /* refill gaps > 6 ms (missed a window) */
volatile uint32_t dbg_max_gap_ms;      /* largest inter-refill gap observed    */
volatile uint16_t dbg_min_read;        /* smallest mono read this run          */
static   uint32_t dbg_prev_tick = 0U;

static inline void dbg_track_refill(uint16_t n)
{
    uint32_t now = HAL_GetTick();

    dbg_refill_calls++;

    /* Detect a late/missed callback: two refills are normally ~5 ms apart.
     * A gap > 6 ms means the DMA likely replayed past a half that was not
     * (or not yet) refilled. */
    if (dbg_refill_calls > 1U)
    {
        int32_t gap = (int32_t)(now - dbg_prev_tick);
        if (gap > 6)
        {
            dbg_late_gap++;
            if ((uint32_t)gap > dbg_max_gap_ms)
            {
                dbg_max_gap_ms = (uint32_t)gap;
            }
        }
    }
    dbg_prev_tick = now;

    if (dbg_min_read == 0U)
    {
        dbg_min_read = I2S_HALF_MONO_COUNT;
    }
    if (n < dbg_min_read)
    {
        dbg_min_read = n;
    }

    /* Short fill = consumer starved for this half-buffer. */
    if (n < I2S_HALF_MONO_COUNT)
    {
        dbg_partial_count++;
        dbg_partial_short += (uint32_t)(I2S_HALF_MONO_COUNT - n);
    }
}

/* Refill the first half of audio_i2s_buffer with samples from the
 * ring. Called every ~5 ms when the DMA finishes the first half. */
void AudioI2S_RefillHalfA(void)
{
    /* Acoustic-isolation diagnostic: bypass USB/ring entirely. */
    if (dbg_bypass_usb)
    {
        audioi2s_fill_generated(I2S_HALF_MONO_COUNT, 0U);
        return;
    }
    /* Step 1: zero the first half. This is the "underrun = silence"
     * policy. If the ring has data, we'll overwrite below; if not,
     * the silence persists. The memset also catches any partial
     * fill correctly (the unfilled tail stays zero).
     *
     * The byte count (I2S_HALF_BYTES) equals the element count, so GCC's
     * -Wmemset-elt-size warns; we ARE filling bytes, so suppress it. */
    _Pragma("GCC diagnostic push")
    _Pragma("GCC diagnostic ignored \"-Wmemset-elt-size\"")
    memset((uint8_t *)audio_i2s_buffer, 0, (size_t)I2S_HALF_BYTES);
    _Pragma("GCC diagnostic pop")

    /* Step 2: pull up to I2S_HALF_MONO_COUNT mono samples from the ring. */
    uint16_t n = RingBuffer_Read(mono_scratch, I2S_HALF_MONO_COUNT);
    dbg_track_refill(n);

    /* Step 3: duplicate each mono sample into L+R slots of the
     * I2S buffer's first half. mono_scratch[0] -> [L,R], [1] -> [L,R], ...
     *
     * i2s_buf[0]     = mono[0]  (L of frame 0)
     * i2s_buf[1]     = mono[0]  (R of frame 0)
     * i2s_buf[2]     = mono[1]  (L of frame 1)
     * i2s_buf[3]     = mono[1]  (R of frame 1)
     * ... */
    for (uint16_t i = 0; i < n; i++) {
        audio_i2s_buffer[2 * i]         = mono_scratch[i];   /* L */
        audio_i2s_buffer[2 * i + 1]     = mono_scratch[i];   /* R */
    }
}

/* Refill the second half. Identical to HalfA but writes start
 * at index 440 (the 221st stereo frame). */
void AudioI2S_RefillHalfB(void)
{
    /* Acoustic-isolation diagnostic: bypass USB/ring entirely. */
    if (dbg_bypass_usb)
    {
        audioi2s_fill_generated(I2S_HALF_MONO_COUNT, I2S_HALF_MONO_COUNT * 2U);
        return;
    }
    /* Zero the second half. Suppress -Wmemset-elt-size (byte count == element count). */
    _Pragma("GCC diagnostic push")
    _Pragma("GCC diagnostic ignored \"-Wmemset-elt-size\"")
    memset((uint8_t *)&audio_i2s_buffer[I2S_HALF_MONO_COUNT * 2], 0, (size_t)I2S_HALF_BYTES);
    _Pragma("GCC diagnostic pop")

    uint16_t n = RingBuffer_Read(mono_scratch, I2S_HALF_MONO_COUNT);
    dbg_track_refill(n);

    /* Write into the second half: i2s_buf[440 + 2i] and [440 + 2i + 1]. */
    uint16_t base = I2S_HALF_MONO_COUNT * 2;   /* 440 */
    for (uint16_t i = 0; i < n; i++) {
        audio_i2s_buffer[base + 2 * i]     = mono_scratch[i];
        audio_i2s_buffer[base + 2 * i + 1] = mono_scratch[i];
    }
}

/* Start the I2S DMA stream. Call this from main.c BEFORE
 * MX_USB_DEVICE_Init() so the peripheral is already clocking
 * out silence when the USB host enumerates and starts streaming. */
void AudioI2S_Init(void)
{
    /* Start the DMA in circular mode. The HAL takes ownership of
     * audio_i2s_buffer and will ping-pong through it, calling our
     * RefillHalfA / RefillHalfB at each half boundary.
     *
     * The size is in 16-bit elements (880 = 440 stereo frames = 10 ms). */
    if (HAL_I2S_Transmit_DMA(&hi2s2, (uint16_t *)audio_i2s_buffer,
                             AUDIO_I2S_BUFFER_SIZE) != HAL_OK) {
        Error_Handler();
    }
}
