/* Core/Src/audio_i2s.c
 *
 * The I2S consumer side of the audio pipeline.
 *
 * DATA FLOW
 * ---------
 *   USB host -> usbd_audio_if.c -> RingBuffer_Write -> ring_buffer
 *   ring_buffer -> [AudioI2S_RefillHalfA/B] -> audio_i2s_buffer
 *   audio_i2s_buffer -> DMA1_Stream4 -> I2S2 -> MAX98357A -> speaker
 *
 * We are the consumer. We pull mono int16 samples out of the
 * ring buffer and lay them into a stereo-shaped I2S DMA buffer
 * (each mono sample written to BOTH the L and R slot of a frame).
 * The MAX98357A mixes L+R internally, so the speaker hears
 * (L+R)/2 = mono_sample with no amplitude loss.
 *
 * CALLBACK ROUTING
 * ----------------
 * The HAL fires HAL_I2S_TxHalfCpltCallback and HAL_I2S_TxCpltCallback
 * from the DMA1_Stream4 ISR. We don't override those weak symbols
 * here — instead, stm32f4xx_it.c dispatches them to our Refill
 * functions. This keeps the ISR dispatch file as the single
 * "what happens on IRQ X" place.
 */

#include "audio_i2s.h"
#include "ring_buffer.h"
#include "stm32f4xx_hal.h"   /* I2S_HandleTypeDef */
#include <string.h>

/* The I2S2 peripheral handle is generated by CubeMX and lives
 * in main.c. We declare it extern here so this module compiles
 * without depending on main.c's internals. */
extern I2S_HandleTypeDef hi2s2;
extern void Error_Handler(void);

/* The I2S DMA buffer. Zero-initialized at startup so the very
 * first samples (before any USB audio arrives) are silence. */
int16_t audio_i2s_buffer[AUDIO_I2S_BUFFER_SIZE] = {0};

/* How many mono samples fit in one I2S half-buffer.
 * Half = 441 int16 = 220 stereo frames = 220 mono samples. */
#define I2S_HALF_MONO_COUNT  (AUDIO_I2S_BUFFER_SIZE / 2 / 2)   /* 220 */
#define I2S_HALF_BYTES       (I2S_HALF_MONO_COUNT * 2 * sizeof(int16_t))  /* 882 */

/* Scratch for pulling mono samples from the ring before duplicating
 * them into L+R. 220 int16 = 220 mono samples = 5 ms of audio at
 * 44.1 kHz = exactly one half of the I2S buffer's worth.
 *
 * Why a scratch instead of writing directly into the I2S buffer:
 * RingBuffer_Read writes samples contiguously (mono), but the I2S
 * buffer needs them duplicated (L, R, L, R, ...). Easier to do the
 * duplication in a second pass over a small scratch array. */
static int16_t mono_scratch[220];

/* Refill the first half of audio_i2s_buffer with samples from the
 * ring. Called every ~5 ms when the DMA finishes the first half. */
void AudioI2S_RefillHalfA(void)
{
    /* Step 1: zero the first half. This is the "underrun = silence"
     * policy. If the ring has data, we'll overwrite below; if not,
     * the silence persists. The memset also catches any partial
     * fill correctly (the unfilled tail stays zero).
     *
     * The cast to size_t is to silence GCC's -Wmemset-elt-size
     * warning: it sees I2S_HALF_BYTES == sizeof(buffer)/2 and
     * suspects we meant "fill half the elements" instead of
     * "fill half the BYTES." We're filling bytes, so cast. */
    memset(audio_i2s_buffer, 0, (size_t)I2S_HALF_BYTES);

    /* Step 2: pull up to I2S_HALF_MONO_COUNT mono samples from the ring. */
    uint16_t n = RingBuffer_Read(mono_scratch, I2S_HALF_MONO_COUNT);

    /* Step 3: duplicate each mono sample into L+R slots of the
     * I2S buffer's first half. mono_scratch[0] -> [L,R], [1] -> [L,R], ...
     *
     * i2s_buf[0]     = mono[0]  (L of frame 0)
     * i2s_buf[1]     = mono[0]  (R of frame 0)
     * i2s_buf[2]     = mono[1]  (L of frame 1)
     * i2s_buf[3]     = mono[1]  (R of frame 1)
     * ... */
    for (uint16_t i = 0; i < n; i++) {
        audio_i2s_buffer[2 * i]         = mono_scratch[i];   /* L */
        audio_i2s_buffer[2 * i + 1]     = mono_scratch[i];   /* R */
    }
}

/* Refill the second half. Identical to HalfA but writes start
 * at index 441 (the 222nd stereo frame). */
void AudioI2S_RefillHalfB(void)
{
    /* Zero the second half. Cast to size_t to silence the same
     * GCC warning as above. */
    memset(&audio_i2s_buffer[I2S_HALF_MONO_COUNT * 2], 0, (size_t)I2S_HALF_BYTES);

    uint16_t n = RingBuffer_Read(mono_scratch, I2S_HALF_MONO_COUNT);

    /* Write into the second half: i2s_buf[441 + 2i] and [441 + 2i + 1]. */
    uint16_t base = I2S_HALF_MONO_COUNT * 2;   /* 441 */
    for (uint16_t i = 0; i < n; i++) {
        audio_i2s_buffer[base + 2 * i]     = mono_scratch[i];
        audio_i2s_buffer[base + 2 * i + 1] = mono_scratch[i];
    }
}

/* Start the I2S DMA stream. Call this from main.c BEFORE
 * MX_USB_DEVICE_Init() so the peripheral is already clocking
 * out silence when the USB host enumerates and starts streaming. */
void AudioI2S_Init(void)
{
    /* Start the DMA in circular mode. The HAL takes ownership of
     * audio_i2s_buffer and will ping-pong through it, calling our
     * RefillHalfA / RefillHalfB at each half boundary.
     *
     * The size is in 16-bit elements (882 = 441 stereo frames = 10 ms). */
    if (HAL_I2S_Transmit_DMA(&hi2s2, (uint16_t *)audio_i2s_buffer,
                             AUDIO_I2S_BUFFER_SIZE) != HAL_OK) {
        Error_Handler();
    }
}
